language: scala

sudo: false

notifications: 
  email: false

jdk:
  - openjdk8
  - openjdk11
  - openjdk14

env:
  matrix:
    - TRAVIS_SBT_VERSION=0.13.16
    - TRAVIS_SBT_VERSION=1.0.4
    - TRAVIS_SBT_VERSION=1.1.6
    - TRAVIS_SBT_VERSION=1.2.8
    - TRAVIS_SBT_VERSION=1.3.10

jobs:
  exclude:
    - jdk: openjdk11
      env: TRAVIS_SBT_VERSION=0.13.16
    - jdk: openjdk14
      env: TRAVIS_SBT_VERSION=0.13.16
    - jdk: openjdk14
      env: TRAVIS_SBT_VERSION=1.0.4
    - jdk: openjdk14
      env: TRAVIS_SBT_VERSION=1.1.6
    - jdk: openjdk14
      env: TRAVIS_SBT_VERSION=1.2.8


script:
  sbt ^^$TRAVIS_SBT_VERSION test scripted