language: scala

sudo: false

notifications: 
  email: false

jdk:
   - oraclejdk8

env:
  matrix:
    - TRAVIS_SBT_VERSION=0.13.17
    - TRAVIS_SBT_VERSION=1.1.6
    - TRAVIS_SBT_VERSION=1.2.8

script:
  sbt ^^$TRAVIS_SBT_VERSION test scripted